---
# install and setup etcd on Debian-based/like distros (apt package manager)
- name: Install needed packages
  ansible.builtin.apt:
    name: "{{ etcd_packages }}"
    state: present
  tags: etcd_install
