---
# install etcd on Alt Linux Server
- name: Install needed packages
  community.general.apt_rpm:
    package: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ etcd_packages }}"
  tags: etcd_install
