---
# install etcd on Alt Linux Server
- name: install needed packages
  ansible.builtin.apt_rpm:
    package: "{{ item }}"
    update_cache: true
    state: present
  loop: "{{ etcd_packages }}"
  tags: etcd_install
