---
- name: Check if ansible version is equal or greater than 2.11
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"
  when: ansible_version.full is ansible.builtin.version('2.11','<')

- name: Check if python is equal or greater than 3
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"
  when: ansible_python.version.major is ansible.builtin.version('3','<')

# tasks file for etcd
# it depends on distros, config file has separate path
- name: Install and setup etcd
  ansible.builtin.include_tasks: "{{ ansible_pkg_mgr }}.yml"
  tags: etcd_init

- name: Configure etcd
  ansible.builtin.template:
    src: "{{ etcd_templates_dir }}/etcd.conf.j2"
    dest: "{{ etcd_config_file }}"
  notify:
  - etcd enable
  - etcd restart
  tags: etcd_config
