---
# handlers file for etcd
- name: Etcd enable
  ansible.builtin.service:
    name: etcd
    enabled: true

- name: Etcd start
  ansible.builtin.service:
    name: etcd
    state: started

- name: Etcd stop
  ansible.builtin.service:
    name: etcd
    state: stopped

- name: Etcd restart
  ansible.builtin.service:
    name: etcd
    state: restarted

- name: Etcd disable
  ansible.builtin.service:
    name: etcd
    state: stopped
    enabled: false
